services:
  - type: web
    name: kronos-back
    runtime: python
    rootDir: datafeed_tester
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 180
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7

  - type: web
    name: kronos-front
    runtime: static
    rootDir: front
    buildCommand: ""
    staticPublishPath: .
